# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: A.Geiersbach
email: annasazi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Notes, and other cool things that I have stumbled upon
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: mecharaptors
github_username:  ageiersbach

# Build settings
markdown: kramdown
